// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjyimtqxpeoxkhxdgsgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqeWltdHF4cGVveGtoeGRnc2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTMzMjIsImV4cCI6MjA3MTQ4OTMyMn0.mszbU0nUcxx9yW7DcWIl9hKvx9wrEmVYFRvWcZsAuTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});